### PR TITLE
Add GitHub Actions configuration file

### PR DESCRIPTION
**Pull request by szabgab**
I have written a blog post explaining this PR https://perlmaven.com/github-actions-for-math-numerical

### CODE REVIEW

**Comment by mkende** [comment]
Thanks a lot Gabor for this.

**Comment by mkende** [comment]
Actually, I think that the issue that you’re seeing with the test deps not being installed is not specific to the tests. No dependencies at all are installed. I switched to verbose output for the `cpanm` call and you can see [here](https://github.com/mkende/math_numerical/actions/runs/3227606294/jobs/5282632307) that cpanm notices that the dependencies are missing, without actually trying to install them.

The issue is that my `Makefile.PL` file had `NO_MYMETA => 1` set, because it does not use any dynamic feature and this seems to confuse `cpanm` because it can’t find any `META` or `MYMETA` file (I suppose that it’s meant to run on the content of a CPAN dist which at least has a `META` file already, as opposed to the git sources which don’t have it).

With that variable removed (and the `--with-recommends --with-suggests` flags added to the cpanm command), all dependencies are now installed correctly without having to list them in the `ci.yml` file.

**Comment by mkende** [comment]
Separately the issue with Windows is that 1. Strawberry perl does not have a very recent Perl and the `make` command has to be customized (typically using `gmake` instead).

**Comment by szabgab** [comment]
Excellent!

**Pull request merged**
